config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: { registrations: 'admins/registrations' }

  get 'home/index'

  get 'posts/search' => 'posts#search', as: 'search_posts'

  resources :posts

  get '/posts' => 'posts#index'

  root 'home#index'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader

  validates :title, presence: true, length: { minimum: 5 }
  validates :text, presence: true, length: { maximum: 275 }

  searchkick

  def search_posts
    {
      title: title
    }
  end
end

app/controllers/admins/confirmations_controller.rb
# frozen_string_literal: true

class Admins::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/admins/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Admins::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/admins/passwords_controller.rb
# frozen_string_literal: true

class Admins::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/admins/registrations_controller.rb
# frozen_string_literal: true

class Admins::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/admins/sessions_controller.rb
# frozen_string_literal: true

class Admins::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/admins/unlocks_controller.rb
# frozen_string_literal: true

class Admins::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    # Prevent CSRF attacks by raising an exception.
    # For APIs, you may want to use :null_session instead.
    protect_from_forgery with: :exception

    def search
      @postsearches = Post.search(params.fetch(:q, "*"))
    end

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
        end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    render layout: "application"
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_admin!, :except => [:show, :index]

  def index
    render layout: "application"
  end

  def new
    @post = Post.new
  end

  def edit
    @post = Post.find(params[:id])
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end

  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post
    else
      render 'edit'
    end
  end

  def show
    @post = Post.find(params[:id])
  end

  def index
    @posts = Post.all
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to posts_path
  end

  def search
    @postsearches = Post.search(params.fetch(:q, "*"))
  end

  private
    def post_params
      params.require(:post).permit(:title, :text, :username, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/index.html.erb
<h1>Welcome to the coolest Posting Platform ever 😎</h1>

<% if admin_signed_in? %>
  <p>Click <%= link_to 'here', new_post_path %> to create a new post.</p>
  <% else %>
  <p>Sure, looking at posts is fun...</p>
  <p>But creating and editing them is better!</p>
  <p>Click <%= link_to 'here', new_admin_session_path %> to Login.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge do Simão</title>
    <%= favicon_link_tag 'logo.ico' %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="menu">
      <div class="menu-left">
        <%= link_to image_tag("logo.ico", :alt => "logo", :class => "logo"), root_path %>
        <% if admin_signed_in? %>
          <span>Hello <%= current_admin.name %>!</span>
        <% end %>
      </div>

      <ul class="nav-link">
        <li><%= link_to 'Posts', controller: '/posts' %></li>
          <% if admin_signed_in? %>
            <li><%= link_to('Account', edit_admin_registration_path) %></li>
            <li><%= link_to('Logout', destroy_admin_session_path, method: :delete) %></li>
          <% else %>
            <li><%= link_to 'Login', new_admin_session_path %></li>
          <% end %>
      </ul>
    </nav>

    <!-- Required Devide Flash Messages -->
    <div class="flash-message notice"><%= notice %></div>
    <div class="flash-message alert"><%= alert %></div>

    <div class="container">
      <%= yield %>
    </div>

  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h4>
        <%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:
      </h4>
        <% @post.errors.full_messages.each do |msg| %>
          <h5><%= msg %></h5>
        <% end %>
    </div>
    <br>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <br>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :text %> <span>(max: 275 characters)</span>
    <br>
    <%= form.text_area :text %>
  </div>

  <div class="field">
    <%= form.label :username %>
    <br>
    <%= form.text_field :username, :value => current_admin.name, :readonly => true %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <br>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<br>
<h4 style="margin-bottom: 12px;">Search for Posts!</h4>
<div class="field">
  <%= form_tag search_posts_path, method: :get do %>
      <%= text_field_tag :q, nil, placeholder: "What are you looking for?..." %>
  <% end %>
</div>

<h1>Recent Posts</h1>
<% if admin_signed_in? %>
  <p>Click <%= link_to 'here', new_post_path %> to create a new post.</p>
  <% else %>
  <p>Please <%= link_to 'Login', new_admin_session_path %> to view, create and edit posts.</p>
<% end %>

<table>
  <tr>
    <th>Thumbnail</th>
    <th>User</th>
    <th>Title</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

  <% @posts.reverse.each do |post| %>
    <tr>
      <td class="image table"><%= image_tag(post.image.url, alt: 'Image', class: 'image thumbnail') if post.image? %></td>
      <td><%= post.username %></td>
      <td><%= post.title %></td>
      <td><%= post.text %></td>
      <td>
        <%= link_to 'Show', post_path(post) %>
        <% if admin_signed_in? %>
          <br>
          <%= link_to 'Edit', edit_post_path(post) %>
          <br>
          <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
      </td>
    </tr>
  <% end %>
</table>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/search.html.erb
<h1>Results</h1>

<table>
  <tr>
    <th>Results</th>
    <th>Image</th>
    <th>User</th>
    <th>Title</th>
  </tr>

  <% @postsearches.each do |postsearch| %>
  <tr>
    <td><%= link_to postsearch.title, postsearch %></td>
    <td class="image table">
      <%= image_tag(postsearch.image.url, alt: 'Image', class: 'image thumbnail') if postsearch.image? %>
    </td>
    <td><%= postsearch.username %></td>
    <td><%= postsearch.title %></td>
  </tr>
  <% end %>
</table>

app/views/posts/show.html.erb
<h1>Here's your post</h1>

<table>
  <tr>
    <th>Image</th>
    <th>User</th>
    <th>Title</th>
    <th>Description</th>
    <th>Actions</th>
  </tr>

  <tr>
    <td class="image table">
      <%= image_tag(@post.image.url, alt: 'Image', class: 'image show') if @post.image? %>
    </td>
    <td><%= @post.username %></td>
    <td><%= @post.title %></td>
    <td><%= @post.text %></td>
    <td>
      <% if admin_signed_in? %>
        <%= link_to 'Edit', edit_post_path(@post) %>
        <br>
        <%= link_to 'Delete', post_path(@post), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% end %>
    </td>
  </tr>
</table>


<p><%= link_to 'Back', controller: '/posts' %></p>